### ISSUE TITLE
作者您好，我发现训练的时候就算 teacher 和 student 的 imgsize 不一样也能跑，请问代码上是如何对齐 imgsize 的呢？

### ISSUE THREAD

**Issue by GGuo555** [huangzongmou/yolov8_Distillation#3]

**Comment by GGuo555** [comment]
实际没有对齐的操作，teacher指导student训练的时候喂入的相同尺寸的数据

**Comment by huangzongmou** [comment]
因为训练的时候输出维度和蒸馏时候没有关联。你蒸馏时候教师模型和学生模型用的同一尺寸数据。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月7日(周四) 上午9:04
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [huangzongmou/yolov8_Distillation] 作者您好，我发现训练的时候就算 teacher 和 student 的 imgsize 不一样也能跑，请问代码上是如何对齐 imgsize 的呢？ (Issue #3)




 
Closed #3 as completed.

**Comment by Joazs** [comment]
尺寸不同也是可以正常训练的吗？

**Comment by huangzongmou** [comment]
您好！您的邮件已收到，尽快给你回复。谢谢                                                      黄总谋！
