### ISSUE TITLE
请问这个项目用的是 yolov8 的哪个版本？

### ISSUE THREAD

**Issue by ArthurRyan0803** [huangzongmou/yolov8_Distillation#7]
该项目 ultralytics 下面 __init__.py 文件里面的版本是：
`__version__ = '8.0.83'`

但是目前官方 main 分支的版本是
`__version__ = '8.0.225'`

我想把你的代码同步到到自己的项目里，请问该项目用的 yolov8 具体是哪个版本的？

**Comment by huangzongmou** [comment]
应该是这个__version__ = '8.0.83'我今年四月份写的。主要你把蒸馏部分的代码挪过去就好了。
